# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: "2"
linters:
  default: all
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/blablatdinov/gotemir
            - github.com/urfave/cli/v3
            - gopkg.in/yaml.v3
    godox:
      keywords:
        - FIXME
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Work via interface only
      # https://www.yegor256.com/2014/11/20/seven-virtues-of-good-object.html#2-he-works-by-contracts
      - path: (.+)\.go$
        text: returns interface
      # Empty line in function is smell
      # https://www.yegor256.com/2014/11/03/empty-line-code-smell.html
      - path: (.+)\.go$
        text: return with no blank line before
      - path: (.+)\.go$
        text: break with no blank line before
      - path: (.+)\.go$
        text: only one cuddle assignment allowed before range statement
      - path: (.+)\.go$
        text: return statements should not be cuddled if block has more than two lines
      - path: (.+)\.go$
        text: Assignments should only be cuddled with other assignments
      - path: (.+)\.go$
        text: only one cuddle assignment allowed before if statement
      - path: (.+)\.go$
        text: if statements should only be cuddled with assignments
      - path: (.+)\.go$
        text: ranges should only be cuddled with assignments used in the iteration
      - path: (.+)\.go$
        text: assignments should only be cuddled with other assignments
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
