# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: 1

gotemir:
  test-free-files:
    - src/cmd/gotemir.go  # test by integration tests
    # fake objects:
    - src/logic/fk_directory.go
    # structures:
    - src/logic/config.go
    # interfaces:
    - src/logic/compared_structures.go
    - src/logic/directory.go
    - src/logic/path.go
    - src/logic/file_name_variants.go
