# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: '3'

tasks:

  docker-setup:
    cmds:
      - docker build -t gotemir-dev .

  docker-bash:
    cmds:
      - docker run -it --rm -v $(pwd):/app --name gotemir-dev gotemir-dev bash

  docker-test:
    cmds:
      - docker run -it --rm -v $(pwd):/app --name gotemir-dev gotemir-dev task unit-tests integration-tests

  docker-lint:
    cmds:
      - docker run -it --rm -v $(pwd):/app --name gotemir-dev gotemir-dev task lint

  docker-fmt:
    cmds:
      - docker run -it --rm -v $(pwd):/app --name gotemir-dev gotemir-dev task fmt

  default:
    desc: "Build pipeline"
    deps:
      - install-deps
      - unit-tests
      - integration-tests
      - lint
      - build

  build:
    desc: "Build the app"
    deps: [install-deps]
    cmds:
      - go build -o dist/gotemir src/cmd/gotemir.go

  install-deps:
    desc: "Install dependencies"
    cmds:
      - go mod tidy
      - uv sync

  unit-tests:
    desc: "Run unit tests"
    vars:
      TEST_NAME: '{{ .CLI_ARGS | default "./..." }}'
    cmds:
      - go test {{.TEST_NAME}} -test.v

  integration-tests:
    desc: "Run integration tests"
    cmds:
      - uv run pytest tests/it/test.py -s

  fmt:
    desc: "Run formatters"
    cmds:
      - go fmt ./...
      - uv run ruff check tests --fix --fix-only

  lint:
    desc: "Run linters"
    cmds:
      - ec
      - yamllint .
      - golangci-lint run
      - go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...
      - uv run ruff check tests
      - uv run mypy tests

  clean:
    desc: "Clean caches"
    cmds:
      - git clean -f -d -x -e .venv
